/**
 * Regenerates WHOLESALE the TypeScript GitHub's OpenAPI descriptor dictates, from the installed @octokit/openapi
 * (the non-dereferenced api.github.com.json, so component names survive). Build time only: neither the descriptor
 * nor this script is bundled.
 *   src/sections/shared/spec-roles.ts  -> the invitation role enums (the PATCH body's, the GET listing's)
 *
 * A path the descriptor no longer carries, or a shape the emitter does not know, ends the run naming it: a
 * descriptor that outgrows the emitter fails the build instead of rendering less than the spec says.
 *   bun run build:openapi             -> writes every output, formatted by biome as the lint expects
 *   test/scripts/gen-openapi.test.ts  -> pins each committed output to a fresh render, and runs under the nightly's
 *                                        @latest install so a descriptor release that moves an enum fails the night
 */

import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { runMain } from "./lib/entry.js";

const ROOT = join(import.meta.dir, "..", "..");

const DESCRIPTOR_PATH = fileURLToPath(
  import.meta.resolve("@octokit/openapi/generated/api.github.com.json"),
);

export interface SchemaNode {
  readonly [key: string]: unknown;
  readonly $ref?: string;
  readonly enum?: readonly unknown[];
  readonly items?: SchemaNode;
  readonly properties?: Readonly<Record<string, SchemaNode>>;
}

export interface Descriptor {
  readonly paths: Readonly<Record<string, Readonly<Record<string, unknown>>>>;
  readonly components: { readonly schemas: Readonly<Record<string, SchemaNode>> };
}

export function loadDescriptor(): Descriptor {
  return JSON.parse(readFileSync(DESCRIPTOR_PATH, "utf8")) as Descriptor;
}

const COMPONENT_REF = "#/components/schemas/";

/** The schema component a `$ref` names; a `$ref` of any other kind (a parameter, a response, a header) is refused. */
export function component(descriptor: Descriptor, ref: string): SchemaNode {
  const name = ref.startsWith(COMPONENT_REF) ? ref.slice(COMPONENT_REF.length) : undefined;
  const schema = name === undefined ? undefined : descriptor.components.schemas[name];
  if (schema === undefined || schema === null) {
    throw new Error(`${ref} names no component schema`);
  }
  return schema;
}

/** OpenAPI ignores a `$ref`'s sibling keywords, so a render from an alias would say less than its target without
 * failing. */
function resolved(descriptor: Descriptor, node: unknown): unknown {
  const ref = (node as Readonly<Record<string, unknown>> | null)?.$ref;
  if (typeof ref !== "string") {
    return node;
  }
  const target = component(descriptor, ref);
  if (typeof target.$ref === "string") {
    throw new Error(`${ref} is a reference to ${target.$ref}, a chain the emitter does not follow`);
  }
  return target;
}

/** A missing step ends the run naming the path up to it, so a descriptor that moved an enum says where. */
function nodeAt(descriptor: Descriptor, path: readonly string[]): SchemaNode {
  let node: unknown = descriptor;
  for (const [index, key] of path.entries()) {
    const next: unknown = (
      resolved(descriptor, node) as Readonly<Record<string, unknown>> | null
    )?.[key];
    if (next === undefined || next === null) {
      throw new Error(`${path.slice(0, index + 1).join(".")} is missing from the descriptor`);
    }
    node = next;
  }
  return resolved(descriptor, node) as SchemaNode;
}

/** An empty enum is refused like a missing one: rendered, the collaborators section would refuse every pending
 * invitation's role. */
export function enumAt(descriptor: Descriptor, path: readonly string[]): string[] {
  const values = nodeAt(descriptor, path).enum;
  const dotted = path.join(".");
  if (!Array.isArray(values) || values.length === 0) {
    throw new Error(`${dotted} carries no enum, or an empty one`);
  }
  return values.map((value) => {
    if (typeof value !== "string") {
      throw new Error(`${dotted} enum member ${JSON.stringify(value)} is not a string`);
    }
    return value;
  });
}

const header = (what: string) => `/**
 * GENERATED by gen-openapi.ts - do not edit. ${what}
 * descriptor; regenerate with \`bun run build:openapi\` after a descriptor bump.
 */
`;

const stringList = (values: readonly string[]) => values.map((v) => JSON.stringify(v)).join(", ");

// --- Roles ----------------------------------------------------------------------------------------------------

export const ROLES_PATH = "src/sections/shared/spec-roles.ts";

const INVITATION_PATH = "/repos/{owner}/{repo}/invitations/{invitation_id}";
const INVITATIONS_PATH = "/repos/{owner}/{repo}/invitations";
const JSON_BODY = ["content", "application/json", "schema"] as const;

export function renderRoles(descriptor: Descriptor): string {
  const settable = enumAt(descriptor, [
    "paths",
    INVITATION_PATH,
    "patch",
    "requestBody",
    ...JSON_BODY,
    "properties",
    "permissions",
  ]);
  const reported = enumAt(descriptor, [
    "paths",
    INVITATIONS_PATH,
    "get",
    "responses",
    "200",
    ...JSON_BODY,
    "items",
    "properties",
    "permissions",
  ]);
  return `${header("The invitation role vocabularies of GitHub's OpenAPI")}
/** The roles the invitation PATCH body accepts: what a pending invitation can be set to. */
export const INVITATION_ROLES: ReadonlySet<string> = new Set([${stringList(settable)}]);

/** The roles the invitation GET listing reports; it can exceed the PATCH's. */
export const REPORTED_INVITATION_ROLES: ReadonlySet<string> = new Set([${stringList(reported)}]);
`;
}

// --- Outputs ------------------------------------------------------------------------------------------------------

export const OUTPUTS: ReadonlyArray<{
  readonly path: string;
  readonly render: (descriptor: Descriptor) => string;
}> = [{ path: ROLES_PATH, render: renderRoles }];

/** The lint judges the committed output like hand-written code, so it is formatted as biome formats a file at `path`. */
export function formatted(path: string, text: string): string {
  const biome = Bun.spawnSync(
    [join(ROOT, "node_modules", ".bin", "biome"), "format", `--stdin-file-path=${path}`],
    { cwd: ROOT, stdin: Buffer.from(text), stdout: "pipe", stderr: "pipe" },
  );
  if (biome.exitCode !== 0) {
    throw new Error(`biome refused the rendered ${path}:\n${biome.stderr.toString()}`);
  }
  return biome.stdout.toString();
}

export function render(output: (typeof OUTPUTS)[number], descriptor: Descriptor): string {
  return formatted(output.path, output.render(descriptor));
}

if (import.meta.main) {
  await runMain("gen-openapi", () => {
    const descriptor = loadDescriptor();
    for (const output of OUTPUTS) {
      writeFileSync(join(ROOT, output.path), render(output, descriptor));
      console.log(`wrote ${output.path}`);
    }
  });
}
