/**
 * GENERATED by gen-openapi.ts - do not edit. The ruleset rule rows of GitHub's OpenAPI
 * descriptor; regenerate with `bun run build:openapi` after a descriptor bump.
 */

import { z } from "zod";
import { RULE_OVERRIDES } from "./rule-overrides.js";

const PatternRuleParameters = z
  .looseObject({
    name: z.string().describe("How this rule appears when configuring it.").optional(),
    negate: z.boolean().describe("If true, the rule will fail if the pattern matches.").optional(),
    operator: z
      .enum(["starts_with", "ends_with", "contains", "regex"])
      .describe("The operator to use for matching."),
    pattern: z.string().describe("The pattern to match with."),
  })
  .meta({
    id: "PatternRuleParameters",
  });

const ReviewDismissalActorConfig = z
  .looseObject({
    id: z.int({ abort: true }).describe("ID of the actor that can dismiss reviews."),
    type: z
      .enum(["User", "Team", "IntegrationInstallation", "RepositoryRole"])
      .describe("The type of the actor"),
  })
  .meta({
    id: "ReviewDismissalActorConfig",
    description: "An actor allowed to dismiss pull request reviews",
  });

const DismissalRestriction = z
  .looseObject({
    allowed_actors: z
      .array(ReviewDismissalActorConfig)
      .describe("Specify people, teams, or apps allowed to dismiss pull request reviews.")
      .optional(),
    enabled: z.boolean().describe("Whether to restrict review dismissal to specific actors."),
  })
  .describe("Specify people, teams, or apps allowed to dismiss pull request reviews.");

const Reviewer = z
  .looseObject({
    id: z
      .int({ abort: true })
      .describe("ID of the reviewer which must review changes to matching files."),
    type: z.literal("Team").describe("The type of the reviewer"),
  })
  .describe("A required reviewing team");

const RequiredReviewerConfig = z
  .looseObject({
    file_patterns: z
      .array(z.string())
      .describe(
        [
          "Array of file patterns. Pull requests which change matching files must be",
          "approved by the specified team. File patterns use fnmatch syntax.",
        ].join(" "),
      ),
    minimum_approvals: z
      .int({ abort: true })
      .describe(
        [
          "Minimum number of approvals required from the specified team. If set to zero,",
          "the team will be added to the pull request but approval is optional.",
        ].join(" "),
      ),
    reviewer: Reviewer,
  })
  .meta({
    id: "RequiredReviewerConfig",
    description: [
      "A reviewing team, and file patterns describing which files they must approve",
      "changes to.",
    ].join(" "),
  });

const StatusCheckConfig = z
  .looseObject({
    context: z
      .string()
      .describe("The status check context name that must be present on the commit."),
    integration_id: z
      .int({ abort: true })
      .describe("The optional integration ID that this status check must originate from.")
      .optional(),
  })
  .meta({
    id: "StatusCheckConfig",
    description: "Required status check",
  });

const WorkflowFileConfig = z
  .looseObject({
    path: z.string().describe("The path to the workflow file"),
    ref: z.string().describe("The ref (branch or tag) of the workflow file to use").optional(),
    repository_id: z
      .int({ abort: true })
      .describe("The ID of the repository where the workflow is defined"),
    sha: z.string().describe("The commit SHA of the workflow file to use").optional(),
  })
  .meta({
    id: "WorkflowFileConfig",
    description: "A workflow that must run for this rule to pass",
  });

const CodeScanningToolConfig = z
  .looseObject({
    alerts_threshold: z
      .enum(["none", "errors", "errors_and_warnings", "all"])
      .describe(
        [
          "The severity level at which code scanning results that raise alerts block a",
          'reference update. For more information on alert severity levels, see "[About',
          "code scanning",
          'alerts](https://docs.github.com/code-security/code-scanning/managing-code-scanning-alerts/about-code-scanning-alerts#about-alert-severity-and-security-severity-levels)."',
        ].join(" "),
      ),
    security_alerts_threshold: z
      .enum(["none", "critical", "high_or_higher", "medium_or_higher", "all"])
      .describe(
        [
          "The severity level at which code scanning results that raise security alerts",
          "block a reference update. For more information on security severity levels, see",
          '"[About code scanning',
          'alerts](https://docs.github.com/code-security/code-scanning/managing-code-scanning-alerts/about-code-scanning-alerts#about-alert-severity-and-security-severity-levels)."',
        ].join(" "),
      ),
    tool: z.string().describe("The name of a code scanning tool"),
  })
  .meta({
    id: "CodeScanningToolConfig",
    description: "A tool that must provide code scanning results for this rule to pass.",
  });

/** One row per rule type the descriptor's rulesets POST and PUT take, in the descriptor's order; parameters are
 * typed and described as it types and describes them, so a wrong casing or bound is refused at parse instead of
 * coming back as a 422, and the published schema carries GitHub's own words where the docs file adds none. */
export const SPEC_RULES = [
  z.looseObject({ type: z.literal("creation") }).meta({
    id: "Rule<creation>",
    description: "Only allow users with bypass permission to create matching refs.",
  }),
  z
    .looseObject({
      type: z.literal("update"),
      parameters: z
        .looseObject({
          update_allows_fetch_and_merge: z
            .boolean()
            .describe("Branch can pull changes from its upstream repository"),
        })
        .optional(),
    })
    .meta({
      id: "Rule<update>",
      description: "Only allow users with bypass permission to update matching refs.",
    }),
  z.looseObject({ type: z.literal("deletion") }).meta({
    id: "Rule<deletion>",
    description: "Only allow users with bypass permissions to delete matching refs.",
  }),
  z.looseObject({ type: z.literal("required_linear_history") }).meta({
    id: "Rule<required_linear_history>",
    description: "Prevent merge commits from being pushed to matching refs.",
  }),
  z
    .looseObject({
      type: z.literal("merge_queue"),
      parameters: z
        .looseObject({
          check_response_timeout_minutes: z
            .int({ abort: true })
            .min(1, { abort: true })
            .max(360, { abort: true })
            .describe(
              [
                "Maximum time for a required status check to report a conclusion. After this much",
                "time has elapsed, checks that have not reported a conclusion will be assumed to",
                "have failed",
              ].join(" "),
            ),
          grouping_strategy: z
            .enum(["ALLGREEN", "HEADGREEN"])
            .describe(
              [
                "When set to ALLGREEN, the merge commit created by merge queue for each PR in the",
                "group must pass all required checks to merge. When set to HEADGREEN, only the",
                "commit at the head of the merge group, i.e. the commit containing changes from",
                "all of the PRs in the group, must pass its required checks to merge.",
              ].join(" "),
            ),
          max_entries_to_build: z
            .int({ abort: true })
            .min(0, { abort: true })
            .max(100, { abort: true })
            .describe(
              [
                "Limit the number of queued pull requests requesting checks and workflow runs at",
                "the same time.",
              ].join(" "),
            ),
          max_entries_to_merge: z
            .int({ abort: true })
            .min(0, { abort: true })
            .max(100, { abort: true })
            .describe("The maximum number of PRs that will be merged together in a group."),
          merge_method: z
            .enum(["MERGE", "SQUASH", "REBASE"])
            .describe("Method to use when merging changes from queued pull requests."),
          min_entries_to_merge: z
            .int({ abort: true })
            .min(0, { abort: true })
            .max(100, { abort: true })
            .describe("The minimum number of PRs that will be merged together in a group."),
          min_entries_to_merge_wait_minutes: z
            .int({ abort: true })
            .min(0, { abort: true })
            .max(360, { abort: true })
            .describe(
              [
                "The time merge queue should wait after the first PR is added to the queue for",
                "the minimum group size to be met. After this time has elapsed, the minimum group",
                "size will be ignored and a smaller group will be merged.",
              ].join(" "),
            ),
        })
        .optional(),
    })
    .meta({
      id: "Rule<merge_queue>",
      description: "Merges must be performed via a merge queue.",
    }),
  z
    .looseObject({
      type: z.literal("required_deployments"),
      parameters: z
        .looseObject({
          required_deployment_environments: z
            .array(z.string())
            .describe(
              [
                "The environments that must be successfully deployed to before branches can be",
                "merged.",
              ].join(" "),
            ),
        })
        .optional(),
    })
    .meta({
      id: "Rule<required_deployments>",
      description: [
        "Choose which environments must be successfully deployed to before refs can be",
        "pushed into a ref that matches this rule.",
      ].join(" "),
    }),
  z.looseObject({ type: z.literal("required_signatures") }).meta({
    id: "Rule<required_signatures>",
    description: "Commits pushed to matching refs must have verified signatures.",
  }),
  z
    .looseObject({
      type: z.literal("pull_request"),
      parameters: z
        .looseObject({
          allowed_merge_methods: z
            .array(z.enum(["merge", "squash", "rebase"]))
            .check(RULE_OVERRIDES.pull_request.allowed_merge_methods)
            .describe(
              [
                "Array of allowed merge methods. Allowed values include `merge`, `squash`, and",
                "`rebase`. At least one option must be enabled.",
              ].join(" "),
            )
            .optional(),
          dismiss_stale_reviews_on_push: z
            .boolean()
            .describe(
              [
                "New, reviewable commits pushed will dismiss previous pull request review",
                "approvals.",
              ].join(" "),
            ),
          dismissal_restriction: DismissalRestriction.optional(),
          require_code_owner_review: z
            .boolean()
            .describe(
              [
                "Require an approving review in pull requests that modify files that have a",
                "designated code owner.",
              ].join(" "),
            ),
          require_last_push_approval: z
            .boolean()
            .describe(
              [
                "Whether the most recent reviewable push must be approved by someone other than",
                "the person who pushed it.",
              ].join(" "),
            ),
          required_approving_review_count: z
            .int({ abort: true })
            .min(0, { abort: true })
            .max(10, { abort: true })
            .describe(
              [
                "The number of approving reviews that are required before a pull request can be",
                "merged.",
              ].join(" "),
            ),
          required_review_thread_resolution: z
            .boolean()
            .describe(
              "All conversations on code must be resolved before a pull request can be merged.",
            ),
          required_reviewers: z
            .array(RequiredReviewerConfig)
            .describe(
              [
                "> [!NOTE]\n> `required_reviewers` is in beta and subject to change.\n\nA collection",
                "of reviewers and associated file patterns. Each reviewer has a list of file",
                "patterns which determine the files that reviewer is required to review.",
              ].join(" "),
            )
            .optional(),
        })
        .optional(),
    })
    .meta({
      id: "Rule<pull_request>",
      description: [
        "Require all commits be made to a non-target branch and submitted via a pull",
        "request before they can be merged.",
      ].join(" "),
    }),
  z
    .looseObject({
      type: z.literal("required_status_checks"),
      parameters: z
        .looseObject({
          do_not_enforce_on_create: z
            .boolean()
            .describe(
              [
                "Allow repositories and branches to be created if a check would otherwise",
                "prohibit it.",
              ].join(" "),
            )
            .optional(),
          required_status_checks: z
            .array(StatusCheckConfig)
            .describe("Status checks that are required."),
          strict_required_status_checks_policy: z
            .boolean()
            .describe(
              [
                "Whether pull requests targeting a matching branch must be tested with the latest",
                "code. This setting will not take effect unless at least one status check is",
                "enabled.",
              ].join(" "),
            ),
        })
        .optional(),
    })
    .meta({
      id: "Rule<required_status_checks>",
      description: [
        "Choose which status checks must pass before the ref is updated. When enabled,",
        "commits must first be pushed to another ref where the checks pass.",
      ].join(" "),
    }),
  z.looseObject({ type: z.literal("non_fast_forward") }).meta({
    id: "Rule<non_fast_forward>",
    description: "Prevent users with push access from force pushing to refs.",
  }),
  z
    .looseObject({
      type: z.literal("commit_message_pattern"),
      parameters: PatternRuleParameters.optional(),
    })
    .meta({
      id: "Rule<commit_message_pattern>",
      description: "Parameters to be used for the commit_message_pattern rule",
    }),
  z
    .looseObject({
      type: z.literal("commit_author_email_pattern"),
      parameters: PatternRuleParameters.optional(),
    })
    .meta({
      id: "Rule<commit_author_email_pattern>",
      description: "Parameters to be used for the commit_author_email_pattern rule",
    }),
  z
    .looseObject({
      type: z.literal("committer_email_pattern"),
      parameters: PatternRuleParameters.optional(),
    })
    .meta({
      id: "Rule<committer_email_pattern>",
      description: "Parameters to be used for the committer_email_pattern rule",
    }),
  z
    .looseObject({
      type: z.literal("branch_name_pattern"),
      parameters: PatternRuleParameters.optional(),
    })
    .meta({
      id: "Rule<branch_name_pattern>",
      description: "Parameters to be used for the branch_name_pattern rule",
    }),
  z
    .looseObject({
      type: z.literal("tag_name_pattern"),
      parameters: PatternRuleParameters.optional(),
    })
    .meta({
      id: "Rule<tag_name_pattern>",
      description: "Parameters to be used for the tag_name_pattern rule",
    }),
  z
    .looseObject({
      type: z.literal("workflows"),
      parameters: z
        .looseObject({
          do_not_enforce_on_create: z
            .boolean()
            .describe(
              [
                "Allow repositories and branches to be created if a check would otherwise",
                "prohibit it.",
              ].join(" "),
            )
            .optional(),
          workflows: z
            .array(WorkflowFileConfig)
            .describe("Workflows that must pass for this rule to pass."),
        })
        .optional(),
    })
    .meta({
      id: "Rule<workflows>",
      description: [
        "Require all changes made to a targeted branch to pass the specified workflows",
        "before they can be merged.",
      ].join(" "),
    }),
  z
    .looseObject({
      type: z.literal("code_scanning"),
      parameters: z
        .looseObject({
          code_scanning_tools: z
            .array(CodeScanningToolConfig)
            .describe("Tools that must provide code scanning results for this rule to pass."),
        })
        .optional(),
    })
    .meta({
      id: "Rule<code_scanning>",
      description: [
        "Choose which tools must provide code scanning results before the reference is",
        "updated. When configured, code scanning must be enabled and have results for",
        "both the commit and the reference being updated.",
      ].join(" "),
    }),
  z
    .looseObject({
      type: z.literal("code_quality"),
      parameters: z
        .looseObject({
          severity: z
            .enum(["errors", "warnings", "notes", "all"])
            .describe(
              [
                "The lowest severity level at which code quality reviews need to be resolved",
                "before commits can be merged.",
              ].join(" "),
            ),
        })
        .optional(),
    })
    .meta({
      id: "Rule<code_quality>",
      description: [
        "Choose which severity levels of code quality results should block pull request",
        "merges. When configured, a code quality analysis must be done on the pull",
        "request before the changes can be merged.",
      ].join(" "),
    }),
  z
    .looseObject({
      type: z.literal("code_coverage"),
      parameters: z
        .looseObject({
          max_coverage_drop: z
            .number()
            .min(0, { abort: true })
            .max(100, { abort: true })
            .describe(
              [
                "The maximum percentage points that line coverage may drop relative to the",
                "default branch. Pull requests that reduce line coverage by more than this amount",
                "will be blocked.",
              ].join(" "),
            )
            .optional(),
          minimum_coverage: z
            .number()
            .min(0, { abort: true })
            .max(100, { abort: true })
            .describe(
              [
                "The absolute minimum line coverage percentage required. Pull requests with line",
                "coverage below this threshold will be blocked.",
              ].join(" "),
            )
            .optional(),
        })
        .optional(),
    })
    .meta({
      id: "Rule<code_coverage>",
      description: [
        "Enforce minimum line coverage thresholds on pull requests. When configured,",
        "uploaded coverage data must meet the specified criteria before changes can be",
        "merged.",
      ].join(" "),
    }),
  z
    .looseObject({
      type: z.literal("copilot_code_review"),
      parameters: z
        .looseObject({
          review_draft_pull_requests: z
            .boolean()
            .describe(
              [
                "Copilot automatically reviews draft pull requests before they are marked as",
                "ready for review.",
              ].join(" "),
            )
            .optional(),
          review_on_push: z
            .boolean()
            .describe("Copilot automatically reviews each new push to the pull request.")
            .optional(),
        })
        .optional(),
    })
    .meta({
      id: "Rule<copilot_code_review>",
      description: [
        "Request Copilot code review for new pull requests automatically if the author",
        "has access to Copilot code review and their premium requests quota has not",
        "reached the limit.",
      ].join(" "),
    }),
  z.looseObject({ type: z.literal("license_compliance_scanning") }).meta({
    id: "Rule<license_compliance_scanning>",
    description: [
      "Enforce any added or changed dependencies to comply with the organization's",
      "license policy.",
    ].join(" "),
  }),
  z
    .looseObject({
      type: z.literal("file_path_restriction"),
      parameters: z
        .looseObject({
          restricted_file_paths: z
            .array(z.string())
            .describe("The file paths that are restricted from being pushed to the commit graph."),
        })
        .optional(),
    })
    .meta({
      id: "Rule<file_path_restriction>",
      description: [
        "Prevent commits that include changes in specified file and folder paths from",
        "being pushed to the commit graph. This includes absolute paths that contain file",
        "names.",
      ].join(" "),
    }),
  z
    .looseObject({
      type: z.literal("max_file_path_length"),
      parameters: z
        .looseObject({
          max_file_path_length: z
            .int({ abort: true })
            .min(1, { abort: true })
            .max(32767, { abort: true })
            .describe("The maximum amount of characters allowed in file paths."),
        })
        .optional(),
    })
    .meta({
      id: "Rule<max_file_path_length>",
      description: [
        "Prevent commits that include file paths that exceed the specified character",
        "limit from being pushed to the commit graph.",
      ].join(" "),
    }),
  z
    .looseObject({
      type: z.literal("file_extension_restriction"),
      parameters: z
        .looseObject({
          restricted_file_extensions: z
            .array(z.string())
            .describe(
              "The file extensions that are restricted from being pushed to the commit graph.",
            ),
        })
        .optional(),
    })
    .meta({
      id: "Rule<file_extension_restriction>",
      description: [
        "Prevent commits that include files with specified file extensions from being",
        "pushed to the commit graph.",
      ].join(" "),
    }),
  z
    .looseObject({
      type: z.literal("max_file_size"),
      parameters: z
        .looseObject({
          max_file_size: z
            .int({ abort: true })
            .min(1, { abort: true })
            .max(100, { abort: true })
            .describe(
              [
                "The maximum file size allowed in megabytes. This limit does not apply to Git",
                "Large File Storage (Git LFS).",
              ].join(" "),
            ),
        })
        .optional(),
    })
    .meta({
      id: "Rule<max_file_size>",
      description: [
        "Prevent commits with individual files that exceed the specified limit from being",
        "pushed to the commit graph.",
      ].join(" "),
    }),
] as const;
